Map kLocationsList = {
  "Egypt": [
    {
      "name": "Aswan",
      "arabicName": "",
      "cities": [
        {
          "name": "Abo ُُ Elresh",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Abu Simbel",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Aswan",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Daraw",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Edfu",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "kalabsha",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "komombo",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "nasral noda",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "rdesiah",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "sahara",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "sebaeiah",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
      ],
    },
    {
      "name": "Asyut",
      "arabicName": "",
      "cities": [
        {
          "name": "Abnub",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Abu Teeg",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Asyut city",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Badari",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Dairut",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Feteh",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Ghanayem",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Manfalut",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "New Assiut",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "New Tiba",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Qusiya",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Sahelselim",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Sedfa",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
      ],
    },
    {
      "name": "Luxor",
      "arabicName": "",
      "cities": [
        {
          "name": "Armant",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Bayadeya",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Isna",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Luxor City",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Qurna",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "Tod",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
        {
          "name": "zinnia",
          "arabicName": "",
          "lat": "",
          "lon": "",
        },
      ],
    },
    {
      "name": "Alexandria",
      "arabicName": "",
      "cities": [
        {"name": "Abu Qir", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Abu Talat", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Agami", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al Hadrah", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al ibrahimiyyah", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Amreya", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Asafra", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Attaril", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Awayed", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Azarita", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Bacchus", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Bahary-anfoshy", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Bolkly", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Borg Al-Arab", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Kamb Caesar", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Sleobatra", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Dekheila", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Dhahira", "arabicName": "", "lat": "", "lon": ""},
        {"name": "El Max", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Fleming", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Gianaclis", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Glimgomrok", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Kabbary", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Kafr Abdo", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Karmous", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Koum Al-Dikka", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Labban", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Laurent", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Maamoura", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Mandara", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Manshiyya", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Miami", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Moharam Bik", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Mont Azah", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Nakheel", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Raml Station", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Ras Al-tin", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Roushdy", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Saba basha", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Salahia", "arabicName": "", "lat": "", "lon": ""},
        {"name": "San Stefano", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Schutz", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Seyouf", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Shatby", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Sidi Beshr", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Sidi Gaber", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Smoha", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Sborting", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Stan", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Victoria", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Wardian", "arabicName": "", "lat": "", "lon": ""},
      ],
    },
    {
      "name": "Ismailia",
      "arabicName": "",
      "cities": [
        {"name": "Abu Swear", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Fayed", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Ismailia City", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Kantara East", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Kantara West", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Qassaseen", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Tal Al-Keber", "arabicName": "", "lat": "", "lon": ""},
      ],
    },
    {
      "name": "Red Sea",
      "arabicName": "",
      "cities": [
        {"name": "Qouna", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Halayeb&Shalateen", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Hurghada", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Marsa Alam", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Qusair", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Ras Qharib", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Safaga", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Sahl hasheesh", "arabicName": "", "lat": "", "lon": ""},
      ],
    },
    {
      "name": "Beheira",
      "arabicName": "",
      "cities": [
        {"name": "Abou homs", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Abuu Al-Matamar", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Damanhour", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Delengat", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Adko", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Etay Al-barud", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Hosa Essa", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Kafr Al-Dawar", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Kom Hamadah", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Mahmoudyah", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Badr", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Nubariyah", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Rahmaniya", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Rashid", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Shubrakhit", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Wadi Al-Natrun", "arabicName": "", "lat": "", "lon": ""},
      ],
    },
    {
      "name": "Giza",
      "arabicName": "",
      "cities": [
        {"name": "6 October", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Abu Rawash", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Ard Al-Lewaa", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Awseen", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Embaba", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al Badrashen", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al Barageel", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al hawamdea", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al Doaae", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al Shekh Zayed", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al Saf", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al Agoza", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al Ayat", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al kit kat", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al Mansouria", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al Moneeb", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al Mohandessen", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al Warak", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Bashtel", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Bolak Al-dakror", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Tersa", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Gezert Al-dahab", "arabicName": "", "lat": "", "lon": ""},
        {"name": "6 October Garden", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Pyrameds Garden ", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Giza", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Dahshor", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Saft Al-Laban", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Garb Somed", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Fessal", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Kerdasa", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Maryoutia", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Manyal sheha", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Nahia", "arabicName": "", "lat": "", "lon": ""},
      ],
    },
    {
      "name": "Dakahlia",
      "arabicName": "",
      "cities": [
        {"name": "Aga", "arabicName": "", "lat": "", "lon": ""},
        {"name": "akhtab", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Semblawen", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Korde", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Manzala", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Mansoura", "arabicName": "", "lat": "", "lon": ""},
        {"name": "New Mansoura", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Belqas", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Bany Aabed", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Temay", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Gamasa", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Dekrnes", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Sherben", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Talkha", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Gamalia", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Mataria", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Meniet Al-Nasr", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Met Slasel", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Met Gamr", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Nabaro", "arabicName": "", "lat": "", "lon": ""},
      ],
    },
    {
      "name": "Suez",
      "arabicName": "",
      "cities": [
        {"name": "El-Aeen El-Sokhna", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Hay Ganayen", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Hay Fessal", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Hay Arbeen", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Hay Swees", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Hay Etaka", "arabicName": "", "lat": "", "lon": ""},
      ],
    },
    {
      "name": "Sharqia",
      "arabicName": "",
      "cities": [
        {"name": "Abu Hamad", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Abu Keber", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Awlad Sakr", "arabicName": "", "lat": "", "lon": ""},
        {"name": "El Ibrahemia", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Hosania", "arabicName": "", "lat": "", "lon": ""},
        {"name": "El zaqazeq", "arabicName": "", "lat": "", "lon": ""},
        {"name": "New Salhia", "arabicName": "", "lat": "", "lon": ""},
        {"name": "10s Ramadan", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al Qareen", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al Enayat", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Belbes", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Darb Negm", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Faqus", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Kafr Sakr", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Mashtol Al-Souq", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Menia Al-Kamh", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Hehia", "arabicName": "", "lat": "", "lon": ""},
      ],
    },
    {
      "name": "Gharbia",
      "arabicName": "",
      "cities": [
        {"name": "El Snata", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Al-Mahla Al-Kobra", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Basyon", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Zefta", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Samanod", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Tanta", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Qtor", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Kaft Al-Zayat", "arabicName": "", "lat": "", "lon": ""},
      ],
    },
    {
      "name": "fayoum",
      "arabicName": "",
      "cities": [
        {"name": "Atsa", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Eshway", "arabicName": "", "lat": "", "lon": ""},
        {"name": "New Fayoum", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Senwrus", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Tamia", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Fayoum City", "arabicName": "", "lat": "", "lon": ""},
        {"name": "Yousef", "arabicName": "", "lat": "", "lon": ""},
      ],
    },
    {
      "name": "Cairo",
      "arabicName": "",
      "cities": [
        {"name": "", "arabicName": "", "lat": "", "lon": ""},
        {"name": "", "arabicName": "", "lat": "", "lon": ""},
        {"name": "", "arabicName": "", "lat": "", "lon": ""},
        {"name": "", "arabicName": "", "lat": "", "lon": ""},
        {"name": "", "arabicName": "", "lat": "", "lon": ""},
        {"name": "", "arabicName": "", "lat": "", "lon": ""},
        {"name": "", "arabicName": "", "lat": "", "lon": ""},
        {"name": "", "arabicName": "", "lat": "", "lon": ""},
        {"name": "", "arabicName": "", "lat": "", "lon": ""},
        {"name": "", "arabicName": "", "lat": "", "lon": ""},
      ],
    },
    {
      "name": "Qalyubia",
      "arabicName": "",
      "cities": [],
    },
    {
      "name": "Monufia",
      "arabicName": "",
      "cities": [],
    },
    {
      "name": "New Valley",
      "arabicName": "",
      "cities": [],
    },
    {
      "name": "Beni Suef",
      "arabicName": "",
      "cities": [],
    },
    {
      "name": "Port Said",
      "arabicName": "",
      "cities": [],
    },
    {
      "name": "South Sinai",
      "arabicName": "",
      "cities": [],
    },
    {
      "name": "Damietta",
      "arabicName": "",
      "cities": [],
    },
    {
      "name": "Sohag",
      "arabicName": "",
      "cities": [],
    },
    {
      "name": "North Sinai",
      "arabicName": "",
      "cities": [],
    },
    {
      "name": "Qena",
      "arabicName": "",
      "cities": [],
    },
    {
      "name": "Qafr Al Sheikh",
      "arabicName": "",
      "cities": [],
    },
    {
      "name": "Matruh",
      "arabicName": "",
      "cities": [],
    },
  ],
};
